_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.4354
  - 44.2383
  - 9
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 12
minzoom: 0
name: Heady T
source: "mapbox:///willpots.3fdf07e7"
styles: 
  - style.mss
template: ''
